version: '3.8'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    ports:
      - "443:443"
    volumes:
      - /home/alucar/data/wordpress_data:/var/www/html
    restart: on-failure
    networks:
      inception:

  wordpress:
    container_name: wp-php
    build: requirements/wordpress/.
    volumes:
      - /home/alucar/data/wordpress_data:/var/www/html
    restart: unless-stopped
    env_file:
      - .env
    networks:
      inception:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    env_file:
      - .env
    volumes:
      - /home/alucar/data/mariadb_data:/var/lib/mysql
    restart: always
    networks:
      inception:

volumes:
  mariadb_data:
    driver: local
networks:
  inception:
    driver: bridge