version: '3.8'

services:
  nginx:
    container_name: nginx
    build: /home/alucar/srcs/requirements/nginx/.
    ports:
      - "443:443"
    volumes:
      - /home/alucar/srcs/web:/var/www/html
    networks:
      inception:

  wordpress:
    container_name: wp-php
    build: /home/alucar/srcs/requirements/wordpress/.
    volumes:
      - /home/alucar/srcs/web:/var/www/html
    env_file:
      - .env
    networks:
      inception:

  mariadb:
    container_name: mariadb
    build: /home/alucar/srcs/requirements/mariadb/.
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      inception:

volumes:
  mariadb_data:
networks:
  inception: